# Generated by Django 5.2.4 on 2025-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginfo",
            name="day_of_week",
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
